services:
  - type: web
    name: book-management-system
    env: dotnet
    plan: free
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/BookManagementSystem.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /health
    autoDeploy: true
