services:
  - type: web
    name: book-management-system
    env: docker
    plan: free
    buildCommand: docker build -t book-management-system .
    startCommand: docker run -p 8080:8080 book-management-system
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: book-management-db
    plan: free
    databaseName: bookmanagementdb
    user: bookmanagementuser 